### ISSUE TITLE
Component stopped working today 2019-06-05

### ISSUE THREAD

**Issue by a94marbo** [ReneNulschDE/ha_cc_mbwebapppy#2]
Error message in components setup in log:

```
Log Details (ERROR)
Wed Jun 05 2019 19:28:04 GMT+0200 (centraleuropeisk sommartid)
Error during setup of component mbwebbeta
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mbwebbeta/__init__.py", line 167, in setup
    mercedesme_api = Controller(username, password, scan_interval)
  File "/config/deps/lib/python3.7/site-packages/mbwebapppy/controller.py", line 212, in __init__
    self._get_cars()
  File "/config/deps/lib/python3.7/site-packages/mbwebapppy/controller.py", line 265, in _get_cars
    response.content.decode('utf8'))['vehicles']
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by plantoschka** [comment]
Same for me.

**Comment by rbr101** [comment]
after updating to latest version of HASS 0.94 it breaks for me too.

**Comment by a94marbo** [comment]
Started to work again today.
